### ISSUE TITLE
Create Rails API project

### ISSUE THREAD

**Issue by igor-chepurnoi** [maksimpanarin/project_x#1]
1. Setup Rails projects, api only application.
2. Push to the current repository.
3. Add README with description of how to setup this project. See example in this repo: https://github.com/igor-chepurnoi/rails-api

Let's use latest versions for ruby + rails, for example ruby: 2.7, rails 6
To install ruby you can use docker or (asdf or rbenv).
To install postgres I suggest to use docker.

You can check example of docker in this repo: https://github.com/igor-chepurnoi/rails-api

**Comment by maksimpanarin** [comment]
Closed
